// Name: Chad Johnson
// Student ID: 1763718
// Email: johns428@mail.chapman.edu
// Name: Jerome Martin
// Student ID: 1851031
// Email: marti368@mail.chapman.edu
// Course: CPSC 390-01
// Assignment: Assignment #2
//Purpose: This class is the readwrite class for the AI pathing project.
//It bookends the AI patthing by first reading an array from a file and then outputing an array to a file.
//It also handles console writes.

#ifndef ReadWrite_H
#define ReadWrite_H
#include <iostream>
#include <fstream>
#include <string>
#include <stdlib.h> 

class ReadWrite
{
public:
	//summary: Takes a filename as input and makes an array of symbols.
	//parammater "filename": the name of the input file.
	//return: returns the character array constructed from the input file.
	char** readFile(std::string filename);
	//summary: Returns the size of the array generated by the read file, indiccated by the first number of the file.
	//return: returns the first number of the read file.
	int sizeOf();
	//summary: Takes an array of characters and prints it to console and writes it to a file.
	//parammater "arr": A pointer for the array being passed.
	//parammater "n": The size of the array.
	void writeFile(char** arr, int n, int p);
private:
	int n;
};

#endif